name: Prepare Java
on: workflow_dispatch
permissions:
  contents: write
jobs:
  java:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: python3 prepare_java.py
